### ISSUE TITLE
UI Configuration

### ISSUE THREAD

**Issue by egandalf** [Geta/InstantTemplates#1]
I've tried this add-on in two sites: One an unaltered, fresh Alloy site, Two an Alloy site that has had content modified and other add-ons installed (PowerSlice, SiteAttention, to name two). 

In the first case, the template management UI shows up alongside Media and Blocks as a new "tab," if you will. 

In the second case, I had to add the template management UI as a Gadget.

While I think the first case is the intended behavior, it should at least be consistent.

Love the add-on!

**Comment by frederikvig** [comment]
From Ben Mckernan (EPiServer):
It occurs when someone has modified their view
e.g. they add a gadget to their view then install the add-on
It's a problem we run into a lot when adding new components and it requires a breaking change to fix hence why it is still a problem.

Workaround for now:
You can create a ViewTransformer that has a SortOrder greater than 10000 (that is when the personalization stuff happens) and in the TransformView method of that you can check to see whether your component has been added, if not add it.

**Comment by frederikvig** [comment]
Can this issue be closed?

**Comment by egandalf** [comment]
Good for me!
