### ISSUE TITLE
Available Instant Templates screen does not scroll when adding 'New from Template'

### ISSUE THREAD

**Issue by MarkMcDonald** [Geta/InstantTemplates#14]
If you have a lot of templates they flow of the bottom of the screen with no way to reach them. By comparing to the standard new page functionality it looks as though the elements needs a height set with the overflow then set to auto. 

In the standard Episerver content panes the widths and heights look to be set in script and tracked on resize, I'm not familiar enough at the minute with some of the epi classes and dojo attach points to know what they hook on to. But looks like in Instant Templates your trying to set the height as 100% and it doesn't appear to work to allow the scroll.

Tested using Chrome.

**Comment by MarkMcDonald** [comment]
Managed to hack together a temporary fix for myself by updating ContentTypeGroup.html adding an inline style to resolve the overflow and height.

`<div class="epi-listingContainer" data-dojo-attach-point="focusNode" tabIndex="${tabIndex}" style="overflow: auto; height: inherit;">
   	<h2 data-dojo-attach-point="titleNode" class="epi-ribbonHeader"></h2>
   	<ul data-dojo-attach-point="containerNode" class="epi-advancedListing"></ul>
</div>
`

**Comment by milosmih92** [comment]
It is fixed in last version (1.0.4).

Kind regards,
Milos Mihajlovic
