### ISSUE TITLE
Available Instant Template options are not updated with each attempt to create a new page

### ISSUE THREAD

**Issue by debpu06** [Geta/InstantTemplates#15]
When selecting "New From Template" for the first time the call is made to the InstantTemplatesStore controller to get the possible template options based on the allowed content types for that parent page. However, when selecting "New From Template" from a different parent page, the InstantTemplateStore controller code is not recalled. So it is only loading allowed template types from the parent page that it received from the first call. This is an issue due to the fact that the second page could have different allowed content types than the first, so they need to be retrieved again.

**Comment by milosmih92** [comment]
This should be fixed with changes for issue #23 .

**Comment by milosmih92** [comment]
It is fixed in last version (1.0.4).

Kind regards,
Milos Mihajlovic
