### ISSUE TITLE
Upgrade to Episerver 11

### ISSUE THREAD

**Issue by Jollebrunjor** [Geta/InstantTemplates#18]
Can you please add support for Episerver 11? :)

**Comment by wiske80** [comment]
When will this be pushed to Nuget?

**Comment by frederikvig** [comment]
It should already be available on Episerver's NuGet feed. Make sure you have include prerelease checked.

**Comment by wiske80** [comment]
![image](https://user-images.githubusercontent.com/7689723/51912900-a84aee80-23d5-11e9-9b3c-c564d225db6c.png)

1.0.3beta is the latest i see...

**Comment by frederikvig** [comment]
Yup, that's the one with Episerver 11 support.
