### ISSUE TITLE
Template is always created with the same parent

### ISSUE THREAD

**Issue by LucasOlssonPF** [Geta/InstantTemplates#23]
If I create a new template page below "About us" everything works as expected.
![bild](https://user-images.githubusercontent.com/36666944/61523416-9fe28080-aa14-11e9-9361-4789c5000f33.png)
Now if I try to add a new template below "Alloy Meet"
![bild](https://user-images.githubusercontent.com/36666944/61523493-c9031100-aa14-11e9-80c7-9c34ef77d4ba.png)
...it still gets added to "About us".
![bild](https://user-images.githubusercontent.com/36666944/61523513-d15b4c00-aa14-11e9-8732-131dff161cdb.png)

It seems that the parent source won't update unless I reload the entire page and I cannot figure out why myself.
We've seen a few bug reports for this on our site.
Your work is much appreciated and thanks for an otherwise great plugin!

**Comment by patkleef** [comment]
Hi @LucasOlssonPF 

We will look into this issue.

**Comment by milosmih92** [comment]
It is fixed in last version (1.0.4).

Kind regards,
Milos Mihajlovic
