### ISSUE TITLE
"New" context menu on Instant Template is confusing. 

### ISSUE THREAD

**Issue by egandalf** [Geta/InstantTemplates#3]
It creates a new template, but seems to me that it would be more logical for this to be another place for a  "New From Template" option. Either way, it just needs clarity for the user.
![screen shot 2015-08-05 at 11 55 20 am 2](https://cloud.githubusercontent.com/assets/1775957/9090600/3570fc72-3b69-11e5-85c3-4f48a849bbff.png)

**Comment by milosmih92** [comment]
James, thank you for your suggestion. We cannot add "New from Template" context option there because we will not know where we should create template instance in page hierarchy (we have no information about instance parent).

Kind regards,
Milos Mihajlovic
