### ISSUE TITLE
Console error when i create a new template

### ISSUE THREAD

**Issue by alna1234** [Geta/InstantTemplates#42]
Hi 

When i create a new template with the plus icon i got a blank page and the below console error apears: 

![image](https://user-images.githubusercontent.com/57388713/68188016-7a1fbe00-ffa8-11e9-8480-ed6b7d06a108.png)

![image](https://user-images.githubusercontent.com/57388713/68188238-0631e580-ffa9-11e9-9cc3-737bec898e0a.png)

Do you know how to resolve it ? 

Thanks in advance

**Comment by milosmih92** [comment]
@alna1234 Thank you for reporting this issue. We resolved it. You will see the change in next version. In the meantime you can create page from template using page context menu in left pane (you can see instructions in https://github.com/Geta/InstantTemplates/blob/master/docs/editor-guide.md )

**Comment by milosmih92** [comment]
@alna1234 We will release minor version with this bugfix and send it to EPiServer this week. After that we will have to wait for EPiServer to make new package version available on their NuGet. I will notify you here when new version of package is available on EPiServer NuGet feed.

**Comment by alna1234** [comment]
Thanks :)

**Comment by Nada90** [comment]
@milosmih92 Hello , Are there any news about the release of a new version of template ?

**Comment by patkleef** [comment]
@Nada90 this is fixed in version 1.1.0. 
https://github.com/Geta/InstantTemplates/blob/develop/CHANGELOG.md#110
