### ISSUE TITLE
[Marketplace] Can not create page from template under content which is created newly from template

### ISSUE THREAD

**Issue by milosmih92** [Geta/InstantTemplates#45]
1. Select a page-1 from page tree
2. Open option context menu > select New from template 
3. Select a available template to create child-page1, do some actions on this page  (editing, publish...)
4. Open option context menu of child-page1 > select New from template under child-page1

Expected: Available templates should be list for creating new one
Actual: Empty list, can not create new page from template. Have to refresh browser then it will be worked.

**Comment by patkleef** [comment]
Fixed in version 1.1.0. 
https://github.com/Geta/InstantTemplates/blob/develop/CHANGELOG.md#110
