### ISSUE TITLE
[Marketplace] Have to refresh site to see new template from list

### ISSUE THREAD

**Issue by milosmih92** [Geta/InstantTemplates#47]
1. Add new page template then publish (or restore new one from trash)
2. Go to page tree, select "Start" node > add new page from template
3. Observer available template list

**Expected**: All templates are listed, includes template at step 1
**Actual**: Only old templates in list, do not see any newly created/restored templates. User has to refresh browser by Ctrl F5 or Logout/login to see completely. See screen record on title link
**Note that if has only few templates, issues does NOT happen.**

**Comment by patkleef** [comment]
Fixed in version 1.1.0. 
https://github.com/Geta/InstantTemplates/blob/develop/CHANGELOG.md#110
