### ISSUE TITLE
[Marketplace] Should not list unpublished content under available templates

### ISSUE THREAD

**Issue by milosmih92** [Geta/InstantTemplates#48]
1. Create some unpublished templates (blocks, page)
2. Select "New from template" under a page

**Expected**: Only published template are listed.
**Actual**: Both published, unpublished are listed. Beside that, do not see any button like "Cancel" for closing list.

**Comment by patkleef** [comment]
Fixed in version 1.1.0. 
https://github.com/Geta/InstantTemplates/blob/develop/CHANGELOG.md#110
