### ISSUE TITLE
[Marketplace] Layout is not nice

### ISSUE THREAD

**Issue by milosmih92** [Geta/InstantTemplates#50]
1. Install CMS site EPiServer.CMS.Core version=11.13.2, EPiServer.CMS.UI version="11.22.1" with Instant template addon
2. Create new content from template

**Expected**: Layout should be displayed nicely
**Actual**: On Creating page, Input name field is not nice (see screenshot)

![image](https://user-images.githubusercontent.com/45643734/71637030-42e12c80-2c3a-11ea-8ff6-1ebcd6350050.png)

**Comment by patkleef** [comment]
Fixed in version 1.1.0. 
https://github.com/Geta/InstantTemplates/blob/develop/CHANGELOG.md#110
