### ISSUE TITLE
[Marketplace] List template is not listed by language version

### ISSUE THREAD

**Issue by milosmih92** [Geta/InstantTemplates#53]
1. Open site in SV language
2. Create new from template
3. Observer available templates

**Expected**: Only "SV" templates are listed
**Actual**: All languages version templates are listed. If create new from "En" then new content in "En" is created.

**Comment by patkleef** [comment]
Fixed in version 1.1.0 => https://github.com/Geta/InstantTemplates/blob/develop/CHANGELOG.md#110
