### ISSUE TITLE
Upgrade to Optimizley CMS 12

### ISSUE THREAD

**Issue by LucasOlssonPF** [Geta/InstantTemplates#71]
Hi,

This is an great plugin and I would love to see an upgrade to support ASP.NET Core / CMS 12. What are your plans to support Optimizley 12?
Thank you.
Kind regards, Lucas

**Comment by frederikvig** [comment]
Version 2.0.0 has been added to the Optimizely NuGet Feed with CMS 12 and .NET 6 support.
