### ISSUE TITLE
Bug with Commerce

### ISSUE THREAD

**Issue by jacobkhan** [Geta/InstantTemplates#8]
WHen you install it with a commerce site the catalog management stops working 
<img width="1280" alt="screen shot 2015-08-16 at 8 22 13 pm" src="https://cloud.githubusercontent.com/assets/11165072/9294669/a3904822-4454-11e5-9089-ff206c346e4a.png">

**Comment by frederikvig** [comment]
Does the same thing happen after you restart the site?

**Comment by jacobkhan** [comment]
Yes, still hapens on oxxstarterkit
