### ISSUE TITLE
Labels when adding new templates

### ISSUE THREAD

**Issue by ethanschofer** [Geta/InstantTemplates#82]
Im not sure where/if I can control this... after installing InstantTemplates, when I try to add a new template, both add options display 'New Block':

![image](https://user-images.githubusercontent.com/7409176/213189188-357d66ba-0b5a-4795-a324-7829e775b361.png)

The second link is for pages. Is there a way I can update this? Like in a language file maybe?

**Comment by frederikvig** [comment]
Looks like it's fixed in [EPiServer.CMS.UI 12.21.0](https://world.optimizely.com/documentation/Release-Notes/ReleaseNote/?releaseNoteId=CMS-27948).
